- name: Taking Inputs from command Line
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "Enter your username"
    private: false

  - name: password
    prompt: "Enter your password"
    private: true
  tasks:
  - name: Print the username
    ansible.builtin.debug:
      msg: "Username : {{ username }}"
  - name: Print the password
    ansible.builtin.debug:
      msg: "Password : {{ password }}" 
